package com.news.entity;
// Generated 2016-4-21 20:48:51 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	@SuppressWarnings("rawtypes")
	private Set newsinfos = new HashSet(0);

	public Topic() {
	}

	public Topic(String title) {
		this.title = title;
	}

	@SuppressWarnings("rawtypes")
	public Topic(String title, Set newsinfos) {
		this.title = title;
		this.newsinfos = newsinfos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@SuppressWarnings("rawtypes")
	public Set getNewsinfos() {
		return this.newsinfos;
	}

	@SuppressWarnings("rawtypes")
	public void setNewsinfos(Set newsinfos) {
		this.newsinfos = newsinfos;
	}

}
