/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`news` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `news`;

DROP TABLE IF EXISTS `admin`;

CREATE TABLE `admin` (
  `Id` int(4) NOT NULL AUTO_INCREMENT,
  `LoginName` VARCHAR(20) NOT NULL,
  `LoginPwd` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `admin`(`LoginName`,`LoginPwd`) VALUES('admin','admin');

DROP TABLE IF EXISTS `topic`;

CREATE TABLE `topic` (
  `Id` int(4) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `topic`(`Id`,`Title`) VALUES('1','国内新闻'),('2','国外新闻'),('3','娱乐新闻'),('4','科技新闻'),('5','社会新闻');

DROP TABLE IF EXISTS `newsinfo`;

CREATE TABLE `newsinfo` (
  `Id` int(4) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(40) NOT NULL,
  `Author` VARCHAR(20) NOT NULL,
  `CreateDate` DATE NOT NULL,
  `Content` VARCHAR(10000) NOT NULL,
  `Summary` VARCHAR(500) NOT NULL,
  `Tid` INT NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `Tid` (`Tid`),
  CONSTRAINT `FK_TOPIC_ID` FOREIGN KEY (`Tid`) REFERENCES `topic` (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;